source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/commons-jexl3-3.2.jar,\
               lib/javax.mail.jar,\
               lib/javax.mail-api-1.6.2.jar,\
               lib/commons-logging-1.2.jar,\
               lib/rhino-1.7.9.jar
