output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/SitracelContratModelValidatorFactory.xml,\
               OSGI-INF/SitracelContratModelValidatorFactory.xml
source.. = src/
