bin.includes = META-INF/,\
               .,\
               OSGI-INF/SitracelRecrutementCalloutFactory.xml,\
               OSGI-INF/SitracelRecrutementCalloutFactory.xml
source.. = src/
output.. = bin/
